### ISSUE TITLE
Entities unresponsive when renaming the charging station

### ISSUE THREAD

**Issue by richardpolzer** [dannerph/homeassistant-keba#10]
When you rename the charging station and choose to rename entities, the entities become unresponsive until the next restart. Then they work as expected.

Is that expected behavior?

HA Version: 2023.3.3
Plugin Version: 3.0.0

**Comment by dannerph** [comment]
Unfortunatelly, I am not able to reproduce this behaviour. With advanced mode enabled and choosing rename entities, all entities are renamed accordingly. The only thing I noticed is that the frontend does not update instantly but needs a refresh in my setup. in the backend (home assistant core) all works as exepcted.

**Comment by richardpolzer** [comment]
You are right. My bad. It was just the UI not reloading. Thanks for your work.
