### ISSUE TITLE
Authentication Sensor not available on RFID Stations

### ISSUE THREAD

**Issue by richardpolzer** [dannerph/homeassistant-keba#11]
With the version 3.0.1 the Authentication sensors disappeared even though all the Charging Stations are equipped with RFID and they are enabled and in use.

Keba Charging Stations in use:
3x Keba P30 c-series RFID, eichrechtskonform
1x Keba P30 x-series RFID, eichrechtskonform
HA Version: 2023.3.3
Plugin Version: 3.0.3

**Comment by dannerph** [comment]
I thought of only adding a lock sensor, if RFID is added to the configuration of the charging station. Without RFID configured, the lock is not working anyhow, at least with my BMW Wallbox Plus. Could you elaborate on how you use the lock?

**Comment by richardpolzer** [comment]
Currently, I use the Lock to determine if the Charging Station (session) is authenticated or not. This allows me to only send the keba.start command to the charging stations that are locked and have an EV connected.

**Comment by dannerph** [comment]
Good point, have not thought of that use case. I will re-add them tomorrow.

**Comment by dannerph** [comment]
Quick fix: add a RFID to the configuration of the device. It should reload the component and add the missing locks.

**Comment by richardpolzer** [comment]
Just as background info on the use case. Here we have an ekey xline Fingerprint sensor. That one sends a request to a webhook on HA. There I find the charging station that I just plugged in and authenticate that one with the RFID set by the finger that was used.
