### ISSUE TITLE
RFID Tag 

### ISSUE THREAD

**Issue by schmersgahoven** [dannerph/homeassistant-keba#19]
Hi all,
ist it possible top integrate RFIG Tag beside RFID class. If someone tells me how I can integrate UDP command to ready actual RFID Tag from Keba in the Files in custom component folder I can also do it in my own.

**Comment by dannerph** [comment]
My BMW Wallbox plus does not provide any RFIT tag as response, even if specificed in the udp programmers guide. Anyhow I can add an optional sensor for it (not sure if it is useful, stating unknown for me)
