### ISSUE TITLE
Lack of support for the Keba Wallbox P30

### ISSUE THREAD

**Issue by TSK7M** [dannerph/homeassistant-keba#27]
Hello, 
unfortunately a lot of data is not evaluated, can the function be extended to include the missing data?
It would be nice if the features were available. 
Unfortunately, it doesn't work for many. As the plugin probably needs to be updated. 

KEBA P30
Firmware: P30 v 3.10.53 (230713-211537)

<img width="249" alt="image" src="https://github.com/dannerph/homeassistant-keba/assets/151848159/471847b4-7a67-4d92-a624-cb6fdcbba182">

Thank you and greetings

**Comment by pos-ei-don** [comment]
Does the p30 Website itself include this data? Do you have a p30 Model which Hasel this data?
My p30 Model does not Provider this Info!

**Comment by TSK7M** [comment]
@pos-ei-don I can see this data on WebIF port 8080 --> Of course, I don't know what interface you're using.

<img width="1885" alt="image" src="https://github.com/dannerph/homeassistant-keba/assets/151848159/9eb11639-9f80-4f5d-be1d-7757b45fc4c4">

<img width="1885" alt="image" src="https://github.com/dannerph/homeassistant-keba/assets/151848159/ad5f5945-faa0-401c-98e2-4574a336da6e">

**Comment by TSK7M** [comment]
KEBA P30 Total energy --> sensor.keba_p30_total_energy

Unfortunately, the entity ID "sensor.keba_p30_total_energy" does not contain any data,
but it would be very interesting to determine the consumption in Home Assistant. How can the value be read?

<img width="974" alt="image" src="https://github.com/dannerph/homeassistant-keba/assets/151848159/d9134809-ccdc-4b96-86e3-49d7028cc713">

**Comment by gerione** [comment]
Which version of the P30 are you using? I am using the P30X and my sensor is populatd. 
![image](https://github.com/dannerph/homeassistant-keba/assets/59999828/f360716e-a372-452b-9e69-9f6c2d615cf9)
![image](https://github.com/dannerph/homeassistant-keba/assets/59999828/e9aca6f7-8f8f-44e6-8d13-b8403cacfad2)

**Comment by TSK7M** [comment]
Thanks for your support.
I have the Kebea:
KC-P30-ES2400E2-L0A-

**Comment by TSK7M** [comment]
KeContact P30 x-series
<img width="728" alt="image" src="https://github.com/dannerph/homeassistant-keba/assets/151848159/71cac62a-7c93-44dd-800b-9e6b52f198c8">

**Comment by gerione** [comment]
So we have the same. Thats really interessting.

**Comment by dannerph** [comment]
Hi @TSK7M 
could you please check again if the DIP switches are correctly set to enable UDP (check your installation manual)?
If I remember correctly, some values, like the session energy, are broadcasted by the charging station and thus interpreted by the home assistant integration. Other values need to be requested first. If the UDP interface is not enabled on the charging station, those requests are ignored.

If that is not working, please provide debug logs
```
logger:
  default: warning
  logs:
    homeassistant.components.keba: debug
    # wrong: keba: debug
    keba_kecontact: debug
```

**Comment by TSK7M** [comment]
Hi @dannerph,
thank you! It was the DSW setting. 
After adjustment, all data was displayed.

----------

<img width="392" alt="image" src="https://github.com/dannerph/homeassistant-keba/assets/151848159/9e91150c-ada3-4ad2-bd8d-bdf48d712437">

**Comment by TSK7M** [comment]
This is a good idea or you should see a message that the configuration is not correct...
