### ISSUE TITLE
[Q] Read state of X1 contact?

### ISSUE THREAD

**Issue by PulsarFX** [dannerph/homeassistant-keba#28]
Is it possible to see the state of X1 contact in the list of sensor values?
I found some hints in the UDP programmers guide, that X1 is transfered, but didn't find a matching sensor in HA. 
These chapters talk about X1: 
2.3 UDP Broadcast Messages
2.6 UDP command „report“

**Comment by dannerph** [comment]
Hi @PulsarFX 
sorry for my late reply. This is already implemented. Check out the optional sensor named "Input"
