### ISSUE TITLE
Support for Keba Wallbox  KeContact P20

### ISSUE THREAD

**Issue by zipperten** [dannerph/homeassistant-keba#30]
The P20 show

In the webpage the values are corect 
![Skärmbild från 2024-06-13 02-01-42](https://github.com/dannerph/homeassistant-keba/assets/4939529/11859339-8beb-4885-a500-2394cd00f561)

With my Nissan Leaf it shows
 
Sensors
Charging: Detected
Charging power: Unknown
Energy target: Unknown
Failsafe mode: Unsafe
Plugged on EV: Plugged in
Session energy: 0,02 kWh
Set current: Unknown
Status: charging
Total energy: Unknown

if i try to control something i get the date in return.
![Skärmbild från 2024-06-13 01-59-04](https://github.com/dannerph/homeassistant-keba/assets/4939529/32297770-95c8-4998-94c8-9e56b49ef295)

Product-ID	KC-P20-ES240010-000-VF -SN:16314558
Software	KEBA P20 v 2.5a3 (160613-061001) : 29309 : 143.0
Service Info	0 : 0
1 : 1 : 0 : 0 : 67 : 12
58 : 1289 : 1970

**Comment by dannerph** [comment]
Hi @zipperten,
have you enabled the udp interface with the DIP settings? Check out the manuel.
