### ISSUE TITLE
Error when restarting while using multiple P30

### ISSUE THREAD

**Issue by richardpolzer** [dannerph/homeassistant-keba#9]
When using this integration with multiple charging stations it works fine while setting up and afterward. Unfortunately on the restart of Home Assistant, the integration is only able to set up the first charging station. The second one becomes unresponsive. Interestingly the second wallbox is now in the integration where only the first wallbox was. The entities all show not available though.

Attached I send some screenshots and debug outputs. Currently, I have 2 charging stations set up. There are 4 keba P30 installed here if that can be of help.

Currently, I'm using HA 2023.3.1 and Plugin Version 2.4.2 installed though HACS as custom repository.

![image](https://user-images.githubusercontent.com/22379225/223676353-285ba078-b710-47ac-9f3b-dc96d7d57620.png)
![image](https://user-images.githubusercontent.com/22379225/223677006-0a47ae62-1c0f-4225-8c2f-d5ec652c1434.png)
![image](https://user-images.githubusercontent.com/22379225/223676398-c9c684ea-594a-4092-9b52-d51f60137c82.png)

Logger: homeassistant.config_entries
Source: custom_components/keba/__init__.py:72
Integration: Keba Charging Station
First occurred: 10:25:09 (1 occurrences)
Last logged: 10:25:09

Error setting up entry P30 for keba
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/keba/__init__.py", line 72, in async_setup_entry
    wallbox = await keba.setup_wallbox(entry.data[CONF_HOST])
  File "/usr/local/lib/python3.10/site-packages/keba_kecontact/connection.py", line 144, in setup_wallbox
    self._wallbox_map[host] = self._wallbox_map.pop(wb.device_info.host)
KeyError: '192.168.xxx.x' _[redacted]_

Logger: homeassistant.components.notify
Source: custom_components/keba/notify.py:39
Integration: Benachrichtigung ([documentation](https://www.home-assistant.io/integrations/notify), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+notify%22))
First occurred: 10:25:10 (1 occurrences)
Last logged: 10:25:10

Error setting up platform keba
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 89, in async_setup_platform
    notify_service = await platform.async_get_service(
  File "/config/custom_components/keba/notify.py", line 31, in async_get_service
    return KebaNotificationService(keba)
  File "/config/custom_components/keba/notify.py", line 39, in __init__
    self.targets: dict[str, Wallbox] = {}
AttributeError: can't set attribute 'targets'

**Comment by slovenec88** [comment]
I see the same behavior with P30X and P30C. If I remove them, and re-add them, they work perfectly until the next restart.  
I tried experimenting with "Enable newly added entities" system settings, before restarting, but it didn't help.

**Comment by dannerph** [comment]
Thanks for reporting, was it working with an older version? I need to check that with my simulated wallboxes again.

**Comment by slovenec88** [comment]
Yes. It was working pre 2.4.0 + pre HA 2023.2.X. Let me know if I can help somehow?

**Comment by dannerph** [comment]
should be fixed in pre-releas 3.0.0, please check and confirm.

**Comment by richardpolzer** [comment]
Thanks for the quick fix. It works even through restarts.
